# Generated by Django 2.2 on 2019-05-03 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('country_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='iso_code', on_delete=django.db.models.deletion.CASCADE, to='mortalidade.Country')),
            ],
            options={
                'db_table': 'mortality',
            },
        ),
    ]
